[project]
authors = ["Rüdiger Braun <Ruediger.Braun@uni-duesseldorf.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mfb2526"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.2,<3"
notebook = ">=7.4.5,<8"
jupyterlab_rise = ">=0.43.1,<0.44"
